# Context

In this notebook we will do a basic data overview to gather more information about the data and the goal of the project.  
Moreover, we will do some data cleaning and data preprocessing steps.

## Project context and goal:

# Load packages

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# from scipy.stats import chi2_contingency
import warnings

warnings.filterwarnings("ignore")
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

# Load data

using relative paths

In [76]:
filename = "data_preprocessing.ipynb"  # Current file name
print(f"Current file name: {filename}\n")
print(f"Current absolute path: {os.getcwd()}\n")

# Specify the paths, relative to the current file
ACTUAL_DIR = os.path.dirname(os.path.abspath(filename))
BASE_DIR = os.path.dirname(ACTUAL_DIR)
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(DATA_DIR, "output_data")

print(f"BASE_DIR: {BASE_DIR}")
print(f"DATA_DIR: {DATA_DIR}")
print(f"OUTPUT_DIR: {OUTPUT_DIR}")

Current file name: data_preprocessing.ipynb

Current absolute path: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera\notebooks

BASE_DIR: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera
DATA_DIR: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera\data
OUTPUT_DIR: c:\Users\jhona\Dropbox\ASPECTOS MAESTRIA\Cursos semestres\SEMESTRE 1\Aprendizaje automatico 1\PROYECTO FINAL\ML1_industria_azucarera\data\output_data

In [77]:
# The HISTORICO_SUERTES.xlsx should be in the data directory
df_base = pd.read_excel(os.path.join(DATA_DIR, "HISTORICO_SUERTES.xlsx"))

# First, lets modify the column names
df_base.columns = [
    x.lower()
    .strip()
    .replace(" ", "_")
    .replace(".", "_")
    .replace("-", "_")
    .replace("(", "")
    .replace(")", "")
    .replace("%", "pct_")
    for x in df_base.columns
]

df_base.head(5)

,período,hacienda,nombre,zona,tenencia,suerte,suelo,area_neta,dist_km,variedad,cod_estado_#,cod_estado,f_siembra,d_s_,ult_riego,edad_ult_cos,f_ult_corte,destino_1=semilla,cod__t_cultivo,cultivo,fec_madur_,producto,dosis_madurante,semanas_mad_,tonultcorte,tch,tchm,ton_azucar,rdto,tah,tahm,sac_caña_precosecha,edad_precosecha,pct_sac_caña,pct_sac_muestreadora,pct_atr,katrhm,pct_fibra_caña,pct_ar_jugo,pct_me_min,pct_me_veg,pct_me_tot,brix,pureza,vejez,tipo_quema,t_corte,cerca_de,cosechó,num_riegos,m3_riego,ddult_riego,lluvias_2_meses_ant_,lluvias_ciclo,lluvias_0__3,lluvias_tres_a_seis,lluvias_seis_a_nueve,luvias_9__fc,pct_infest_diatrea,fosfato_jugo,fert_nitrogen_,urea_46pct_,mez,boro_granul_,microzinc,nito_xtend,sul_amonio,nitrax_s,vinaza,codigo_estacion,temp__media_0_3,temp__media_ciclo,temp_max_ciclo,temp_min_ciclo,humedad_rel_media_0_3,humedad_rel_media_ciclo,oscilacion_temp_med_0_3,oscilacion_temp_ciclo,sum_oscilacion_temp_ciclo,radicion_solar_0_3,radiacion_solar_ciclo,precipitacion_0_3,precipitacion_ciclo,evaporacion_0_3,evaporacion_ciclo
0,201701,80493,LA CONCHA,IP02,51.0,002A,CANTARINA,6.00,4.3,CC85-92,5,Corte 5,2010-08-20,NaN,NaT,12.81,2017-01-02,0,1.0,Normal,2016-11-04,BONUS 250 EC REGULADOR FISIOLÓGICO,1.0,8.428571,727.19,121.198333,9.461228,86.050,11.8332,14.341666,1.119567,16.8172,NaN,13.7582,13.508,15.1653,1434.823641,16.910,0.84,0.355,10.198,10.553,15.7464,87.2241,2.735,VERDE,MECANIZADO,El Cerrito,AI08,NaN,0.0,0,258.0,1038.0,0.0,454.0,102.0,482.0,NaN,178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201701,81284,UKRANIA INCAUCA,IP05,81.0,039B,NaN,1.45,NaN,CC85-92,5,Corte 5,2011-01-27,NaN,NaT,11.14,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,136.00,93.793103,8.419488,14.728,10.8294,10.157241,0.911781,NaN,NaN,12.8430,12.551,14.0410,1182.180399,16.936,0.55,2.298,7.273,9.571,15.2240,84.3602,73.823,Q.ACCIDENTAL,MANUAL,Candelaria,AI08,NaN,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,382.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201701,80203,EL AMPARO SAA,IP05,31.0,007,CORINTIAS,8.24,23.0,CC01-1228,4,Corte 4,2011-10-25,1.65,2016-09-17,12.32,2017-01-02,0,1.0,Normal,2016-11-04,BONUS 250 EC REGULADOR FISIOLÓGICO,1.1,8.428571,1436.62,174.347087,14.151549,145.268,10.1117,17.629611,1.430974,14.7749,12.02,11.9364,11.940,13.1236,1857.192723,15.512,0.61,3.000,9.323,12.323,14.1130,84.4527,2.108,VERDE,MECANIZADO,Palmira,AI08,5.0,48513.6,107,246.0,1002.0,106.0,326.0,113.0,457.0,NaN,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201701,81380,SAN JUDAS INCAUCA,IP05,82.0,013A,NaN,1.05,66.5,CC01-1940,2,Corte 2,2014-03-08,NaN,NaT,9.79,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,143.63,136.790476,13.972469,13.517,9.4109,12.873333,1.314947,NaN,NaN,11.2770,10.931,12.4820,1744.043640,17.621,0.67,0.140,6.788,6.927,13.6350,82.7062,64.614,Q.ACCIDENTAL,MANUAL,Corinto,AI08,NaN,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,278.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201701,80298,JAVA,IP06,31.0,025A,GALPON,4.53,17.0,RB73-2223,3,Corte 3,2013-01-10,1.65,NaT,11.53,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,512.20,113.068432,9.806455,42.505,8.2985,9.383002,0.813790,16.7662,NaN,10.2160,10.294,11.6030,1137.843039,14.352,0.95,0.592,2.939,3.531,12.9760,78.7299,71.021,Q.ACCIDENTAL,MANUAL,Guacari,AI08,NaN,0.0,0,138.0,991.0,264.0,255.0,188.0,284.0,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
df_base.columns

Index(['período', 'hacienda', 'nombre', 'zona', 'tenencia', 'suerte', 'suelo',
       'area_neta', 'dist_km', 'variedad', 'cod_estado_#', 'cod_estado',
       'f_siembra', 'd_s_', 'ult_riego', 'edad_ult_cos', 'f_ult_corte',
       'destino_1=semilla', 'cod__t_cultivo', 'cultivo', 'fec_madur_',
       'producto', 'dosis_madurante', 'semanas_mad_', 'tonultcorte', 'tch',
       'tchm', 'ton_azucar', 'rdto', 'tah', 'tahm', 'sac_caña_precosecha',
       'edad_precosecha', 'pct_sac_caña', 'pct_sac_muestreadora', 'pct_atr',
       'katrhm', 'pct_fibra_caña', 'pct_ar_jugo', 'pct_me_min', 'pct_me_veg',
       'pct_me_tot', 'brix', 'pureza', 'vejez', 'tipo_quema', 't_corte',
       'cerca_de', 'cosechó', 'num_riegos', 'm3_riego', 'ddult_riego',
       'lluvias_2_meses_ant_', 'lluvias_ciclo', 'lluvias_0__3',
       'lluvias_tres_a_seis', 'lluvias_seis_a_nueve', 'luvias_9__fc',
       'pct_infest_diatrea', 'fosfato_jugo', 'fert_nitrogen_', 'urea_46pct_',
       'mez', 'boro_granul_', 'microzinc', 'nito_xtend', 'sul_amonio',
       'nitrax_s', 'vinaza', 'codigo_estacion', 'temp__media_0_3',
       'temp__media_ciclo', 'temp_max_ciclo', 'temp_min_ciclo',
       'humedad_rel_media_0_3', 'humedad_rel_media_ciclo',
       'oscilacion_temp_med_0_3', 'oscilacion_temp_ciclo',
       'sum_oscilacion_temp_ciclo', 'radicion_solar_0_3',
       'radiacion_solar_ciclo', 'precipitacion_0_3', 'precipitacion_ciclo',
       'evaporacion_0_3', 'evaporacion_ciclo'],
      dtype='object')

# Data dictionary

Although there is no official dictionary of the columns of the data set, we can make the following interpretations based on the theory and terms of the sugar sector:

In [1]:
variables_dict = {
    "período": "Periodo de análisis o cosecha",
    "hacienda": "codigo de la hacienda o finca donde se cultiva la caña",
    "nombre": "Nombre de la hacienda o finca",
    "zona": "ID Zona o ubicación del cultivo",
    "tenencia": "Por definir",
    "suerte": "Identificación de la unidad productiva dentro de la hacienda",
    "suelo": "Tipo de suelo donde se cultiva la caña",
    "area_neta": "Área neta cultivada en hectáreas",
    "dist_km": "Distancia en kilómetros al ingenio azucarero o punto de procesamiento",
    "variedad": "Variedad de caña de azúcar cultivada",
    "cod_estado_#": "Código numérico del estado del cultivo. Consecutivo de cosechas",
    "cod_estado": "Descripción del estado del cultivo. Consecutivo de cosechas",
    "f_siembra": "Fecha de siembra del cultivo",
    "d_s_": "Días desde la siembra hasta el análisis actual",
    "ult_riego": "Fecha del último riego aplicado",
    "edad_ult_cos": "Edad del cultivo en el momento de la última cosecha",
    "f_ult_corte": "Fecha del último corte del cultivo",
    "destino_1=semilla": "Indica si la cosecha se destinó a semilla (1) o producción (0)",
    "cod__t_cultivo": "Código del tipo de cultivo",
    "cultivo": "Tipo de cultivo ()",
    "fec_madur_": "Fecha estimada de maduración de la caña",
    "producto": "Tipo de producto o madurante aplicado",
    "dosis_madurante": "Dosis del madurante/producto aplicado (L/ha)",
    "semanas_mad_": "Número de semanas desde la aplicación del madurante hasta la cosecha",
    "tonultcorte": "Toneladas de caña cosechadas en el último corte",
    "tch": "Toneladas de caña por hectárea",
    "tchm": "Toneladas de caña por hectárea en maduración",
    "ton_azucar": "Toneladas de azúcar obtenidas",
    "rdto": "Rendimiento de extracción de azúcar (%)",
    "tah": "Toneladas de azúcar por hectárea",
    "tahm": "Toneladas de azúcar por hectárea en maduración",
    "sac_caña_precosecha": "Porcentaje de sacarosa en caña antes de la cosecha",
    "edad_precosecha": "Edad del cultivo antes de la cosecha en meses",
    "pct_sac_caña": "Porcentaje de sacarosa en caña cosechada",
    "pct_sac_muestreadora": "Porcentaje de sacarosa determinado por muestreo",
    "pct_atr": "Azúcar total recuperable (%)",
    "katrhm": "Kilogramos de azúcar total recuperable por hectárea",
    "pct_fibra_caña": "Porcentaje de fibra en la caña",
    "pct_ar_jugo": "Porcentaje de azúcar reductora en el jugo",
    "pct_me_min": "Porcentaje de materia extraña mineral",
    "pct_me_veg": "Porcentaje de materia extraña vegetal",
    "pct_me_tot": "Porcentaje total de materia extraña",
    "brix": "Contenido de sólidos solubles en el jugo de caña (%)",
    "pureza": "Pureza del jugo de caña (%)",
    "vejez": "por definir",  # Grado de envejecimiento del cultivo
    "tipo_quema": "Tipo de quema antes de la cosecha (si aplica)",
    "t_corte": "Técnica de corte utilizada en la cosecha",
    "cerca_de": "Ubicación de la parcela respecto a un punto de referencia",
    "cosechó": "Por definir",
    "num_riegos": "Número de riegos aplicados durante el ciclo",
    "m3_riego": "Cantidad de agua aplicada en riego (m³)",
    "ddult_riego": "Días desde el último riego hasta la cosecha",
    "lluvias_2_meses_ant_": "Precipitación en los dos meses anteriores a la cosecha (mm)",
    "lluvias_ciclo": "Precipitación acumulada en todo el ciclo de cultivo (mm)",
    "lluvias_0__3": "Lluvias registradas en los primeros 3 meses del ciclo (mm)",
    "lluvias_tres_a_seis": "Lluvias registradas entre los meses 3 y 6 (mm)",
    "lluvias_seis_a_nueve": "Lluvias registradas entre los meses 6 y 9 (mm)",
    "luvias_9__fc": "Lluvias registradas entre los meses 9 y la fecha de cosecha (mm)",
    "pct_infest_diatrea": "Porcentaje de infestación de la plaga Diatraea",
    "fosfato_jugo": "Contenido de fosfato en el jugo de caña",
    "fert_nitrogen_": "Cantidad de fertilizante nitrogenado aplicado",
    "urea_46pct_": "Cantidad de urea (46% N) aplicada",
    "mez": "Por definir",
    "boro_granul_": "Cantidad de boro granular aplicado",
    "microzinc": "Cantidad de zinc aplicado",
    "nito_xtend": "Cantidad de fertilizante Nito Xtend aplicado",
    "sul_amonio": "Cantidad de sulfato de amonio aplicado",
    "nitrax_s": "Cantidad de Nitrax-S aplicado",
    "vinaza": "Cantidad de vinaza aplicada al cultivo",
    "codigo_estacion": "Por definir",  #'Código de la estación meteorológica más cercana'
    "temp__media_0_3": "Temperatura media en los primeros 3 meses del ciclo (°C)",
    "temp__media_ciclo": "Temperatura media durante todo el ciclo (°C)",
    "temp_max_ciclo": "Temperatura máxima registrada durante el ciclo (°C)",
    "temp_min_ciclo": "Temperatura mínima registrada durante el ciclo (°C)",
    "humedad_rel_media_0_3_": "Humedad relativa media en los primeros 3 meses (%)",
    "humedad_rel_media_ciclo": "Humedad relativa media durante todo el ciclo (%)",
    "oscilacion_temp_med_0_3": "Oscilación térmica media en los primeros 3 meses (°C)",
    "oscilacion_temp_ciclo": "Oscilación térmica media durante el ciclo (°C)",
    "sum_oscilacion_temp_ciclo": "Suma de la oscilación térmica durante todo el ciclo (°C)",
    "radicion_solar_0_3": "Radiación solar en los primeros 3 meses (MJ/m²)",
    "radiacion_solar_ciclo": "Radiación solar durante todo el ciclo (MJ/m²)",
    "precipitacion_0_3": "Precipitación acumulada en los primeros 3 meses (mm)",
    "precipitacion_ciclo": "Precipitación total durante el ciclo (mm)",
    "evaporacion_0_3": "Evaporación en los primeros 3 meses (mm)",
    "evaporacion_ciclo": "Evaporación total durante todo el ciclo (mm)",
}

# Base check & data cleaning

-->

In [80]:
df = df_base.copy()

## general

### Formats and NAN values

In [81]:
temp = pd.DataFrame(df.isna().sum().sort_values(ascending=False)).rename(
    columns={0: "nan_obs"}
)
temp["pct_nan"] = round((temp["nan_obs"] / df.shape[0]) * 100, 1)
temp["format"] = [df[var].dtype for var in temp.index.tolist()]
temp

                           nan_obs  pct_nan          format
sum_oscilacion_temp_ciclo    21027    100.0         float64
fert_nitrogen_               21027    100.0         float64
urea_46pct_                  20304     96.6         float64
nitrax_s                     20279     96.4         float64
mez                          20056     95.4         float64
microzinc                    19878     94.5         float64
boro_granul_                 19742     93.9         float64
sul_amonio                   19670     93.5         float64
nito_xtend                   17348     82.5         float64
vinaza                       16929     80.5         float64
humedad_rel_media_ciclo      16497     78.5         float64
temp__media_0_3              16497     78.5         float64
oscilacion_temp_med_0_3      16497     78.5         float64
temp__media_ciclo            16497     78.5         float64
temp_max_ciclo               16497     78.5         float64
humedad_rel_media_0_3        16497     78.5         float64
radiacion_solar_ciclo        16497     78.5         float64
evaporacion_0_3              16497     78.5         float64
precipitacion_ciclo          16497     78.5         float64
evaporacion_ciclo            16497     78.5         float64
temp_min_ciclo               16497     78.5         float64
oscilacion_temp_ciclo        16497     78.5         float64
radicion_solar_0_3           16497     78.5         float64
precipitacion_0_3            16497     78.5         float64
pct_infest_diatrea           15427     73.4         float64
codigo_estacion              14742     70.1          object
d_s_                         13859     65.9          object
num_riegos                   12589     59.9         float64
ult_riego                    12557     59.7  datetime64[ns]
edad_precosecha              12108     57.6         float64
producto                      9778     46.5          object
fec_madur_                    9775     46.5  datetime64[ns]
semanas_mad_                  9775     46.5         float64
suelo                         3758     17.9          object
vejez                         2445     11.6         float64
pct_ar_jugo                   2124     10.1         float64
pct_sac_muestreadora          1858      8.8         float64
fosfato_jugo                  1858      8.8         float64
pct_fibra_caña                1858      8.8         float64
pct_me_min                    1722      8.2         float64
pct_me_veg                    1720      8.2         float64
pct_me_tot                    1720      8.2         float64
sac_caña_precosecha           1098      5.2         float64
pct_atr                        522      2.5         float64
katrhm                         522      2.5         float64
pct_sac_caña                   449      2.1         float64
pureza                         269      1.3         float64
rdto                           267      1.3         float64
brix                           267      1.3         float64
tah                            241      1.1         float64
ton_azucar                     241      1.1         float64
tahm                           241      1.1         float64
cerca_de                       126      0.6          object
dosis_madurante                104      0.5         float64
dist_km                          5      0.0         float64
cod__t_cultivo                   2      0.0         float64
cultivo                          2      0.0          object
tenencia                         1      0.0         float64
variedad                         0      0.0          object
edad_ult_cos                     0      0.0         float64
area_neta                        0      0.0         float64
suerte                           0      0.0          object
hacienda                         0      0.0           int64
nombre                           0      0.0          object
zona                             0      0.0          object
período                          0      0.0           int64
cod_estado_#                     0      0.0           int64
cod_estado                       0      0.0          object
f_siembra                        0      0.0  datetime64[ns]
destino_1=semilla                0      0.0           int64
f_ult_corte                      0      0.0  datetime64[ns]
lluvias_2_meses_ant_             0      0.0         float64
cosechó                          0      0.0          object
tipo_quema                       0      0.0          object
t_corte                          0      0.0          object
tonultcorte                      0      0.0         float64
tchm                             0      0.0         float64
tch                              0      0.0         float64
ddult_riego                      0      0.0           int64
m3_riego                         0      0.0         float64
lluvias_seis_a_nueve             0      0.0         float64
luvias_9__fc                     0      0.0         float64
lluvias_tres_a_seis              0      0.0         float64
lluvias_0__3                     0      0.0         float64
lluvias_ciclo                    0      0.0         float64

**Comments**

--> We have a **total number of 85 variables**. According to the context, we can note groups of variables, for example:
- Farm and soil information
- Crop characteristics
- Crop maturity
- Before harvest
- Irrigation characteristics
- Weather conditions 
- Fertilization and supplements
- And finally, we have several metrics of crop performance (**after harvest**), i.e., TCH, sucrose percentage, among others.

--> The **columns have different formats**, some were identified as datetime type, others as integer or decimal type and others as object/categorical type variables. We will modify some columns formats in next steps.

--> As for the **presence of null values**, we noted variables with more than 80% of null observations and others with less than 10%. We can observe that groups of variables present a very similar amount of nulls, for example, the variables of crop maturity present a percentage close to 47%, variables of applied fertilizers have a percentage of more than 80% and variables of meteorological conditions present a percentage of nulls of approximately 78.5%. This should be taken into account when making decisions on the imputation, inclusion or elimination of variables.

**Cleaning actions**
1. We must keep in mind that the variables to be studied and predicted are only two: Tons of cane per hectare (TCH) and sucrose percentage of cane harvested (pct_sac_cane).  
Therefore, **all the other variables of the harvest performance metrics group should be removed**, in order to **avoid problems such as data leakage** or similar.  
Also, the variables that could be measure only after harvests, should be removed.
2. We will drop he columns with %100 of nan values (sum_oscilacion_temp_ciclo, fert_nitrogen_)

#### cleaning

In [ ]:
var_to_remove = [
    "tonultcorte",
    "tchm",
    "ton_azucar",
    "rdto",
    "tah",
    "tahm",
    "sac_caña_precosecha",
    "pct_sac_muestreadora",
    "pct_atr",
    "katrhm",
    "pct_fibra_caña",
    "pct_ar_jugo",
    "pct_me_min",
    "pct_me_veg",
    "pct_me_tot",
    "brix",
    "pureza",
    "fosfato_jugo",
]

# drop columns that are metrics after harvest
df = df.drop(var_to_remove, axis=1)

# drop columns with only NAN values
df = df.drop(["sum_oscilacion_temp_ciclo", "fert_nitrogen_"], axis=1)


print(f"Number of columns: {df.shape[1]}")

Number of columns: 66

In [83]:
df.columns

Index(['período', 'hacienda', 'nombre', 'zona', 'tenencia', 'suerte', 'suelo',
       'area_neta', 'dist_km', 'variedad', 'cod_estado_#', 'cod_estado',
       'f_siembra', 'd_s_', 'ult_riego', 'edad_ult_cos', 'f_ult_corte',
       'destino_1=semilla', 'cod__t_cultivo', 'cultivo', 'fec_madur_',
       'producto', 'dosis_madurante', 'semanas_mad_', 'tch', 'edad_precosecha',
       'pct_sac_caña', 'vejez', 'tipo_quema', 't_corte', 'cerca_de', 'cosechó',
       'num_riegos', 'm3_riego', 'ddult_riego', 'lluvias_2_meses_ant_',
       'lluvias_ciclo', 'lluvias_0__3', 'lluvias_tres_a_seis',
       'lluvias_seis_a_nueve', 'luvias_9__fc', 'pct_infest_diatrea',
       'fosfato_jugo', 'urea_46pct_', 'mez', 'boro_granul_', 'microzinc',
       'nito_xtend', 'sul_amonio', 'nitrax_s', 'vinaza', 'codigo_estacion',
       'temp__media_0_3', 'temp__media_ciclo', 'temp_max_ciclo',
       'temp_min_ciclo', 'humedad_rel_media_0_3', 'humedad_rel_media_ciclo',
       'oscilacion_temp_med_0_3', 'oscilacion_temp_ciclo',
       'radicion_solar_0_3', 'radiacion_solar_ciclo', 'precipitacion_0_3',
       'precipitacion_ciclo', 'evaporacion_0_3', 'evaporacion_ciclo'],
      dtype='object')

### Identification - obs identifier

--> This exploration is **to find any possible duplicated observation**, and to find out what could be the identification of one valid observation.

In [84]:
print(f"A farm (hacienda) could have more than one harvest period:\n")
print(
    df.groupby(by="hacienda")
    .agg({"período": lambda x: x.nunique()})
    .sort_values(by="período", ascending=False)
    .rename(columns={"período": "#periodos"})
)

A farm (hacienda) could have more than one harvest period:

          #periodos
hacienda
80114            75
81363            73
80111            67
80121            67
80108            67
...             ...
81768             1
81769             1
81044             1
81046             1
81318             1

[926 rows x 1 columns]

In [85]:
print(
    f"A farm (hacienda) could have one or two different zones (zona):\ni.e. Farm id #80134 zones:\n"
)
print(df[(df["hacienda"] == 80134)].zona.value_counts())
print(f"\nGeneral:\n")
print(
    df.groupby(by="hacienda")
    .agg({"zona": lambda x: x.nunique()})
    .sort_values(by="zona", ascending=False)
    .rename(columns={"zona": "#zonas"})
    .iloc[5:15, :]
)

A farm (hacienda) could have one or two different zones (zona):
i.e. Farm id #80134 zones:

zona
IP05    46
IP01    17
Name: count, dtype: int64

General:

          #zonas
hacienda
80601          2
81455          2
82517          2
82524          2
80105          1
80106          1
80107          1
80108          1
80109          1
80110          1

In [86]:
print(
    f"A combination of farm-zone could have one or two different 'tenencia' values:\n(This could be due to a change in the form of land tenure)"
)
df.groupby(by=["hacienda", "zona"]).agg(
    {
        "tenencia": [
            ("#", lambda x: x.nunique()),
            ("names", lambda x: x.unique().tolist()),
        ]
    }
).sort_values(by=[("tenencia", "#"), "hacienda"], ascending=[False, False]).iloc[
    10:20:, :
]

A combination of farm-zone could have one or two different 'tenencia' values:
(This could be due to a change in the form of land tenure)

              tenencia
                     #         names
hacienda zona
81364    IP05        2  [81.0, 51.0]
81363    IP05        2  [81.0, 51.0]
81362    IP05        2  [81.0, 51.0]
81361    IP05        2  [81.0, 51.0]
81313    IP05        2  [81.0, 51.0]
81304    IP03        2  [81.0, 51.0]
81216    IP05        2  [82.0, 81.0]
81191    IP03        2  [81.0, 51.0]
81143    IP06        2  [81.0, 51.0]
81132    IP02        2  [81.0, 51.0]

In [87]:
print(f"Moreover, a combination of farm-zone could have more than one plot (suerte):\n")

df.groupby(by=["hacienda", "zona"]).agg(
    {
        "suerte": [
            ("#", lambda x: x.nunique()),
            ("names", lambda x: x.unique().tolist()),
        ]
    }
)

Moreover, a combination of farm-zone could have more than one plot (suerte):

              suerte
                   #                                              names
hacienda zona
80100    IP01      2                                        [001, 001A]
80101    IP01     78  [010Z, 012, 019C, 002B, 011, 001A, 013B, 010E,...
80102    IP01    108  [050A, 068E, 081C, 067C, 073C, 075B, 076A, 080...
80103    IP01     63  [114B, 119B, 121B, 118D, 106A, 121C, 121E, 117...
80104    IP02     32  [162, 152C, 164A, 165, 158, 151, 158Z, 154T, 1...
...              ...                                                ...
82550    IP06      5                         [002, 005, 007, 007A, 012]
82551    IP02      4                             [002, 003, 003A, 003B]
82552    IP01      6                    [041, 034, 042, 042A, 044, 043]
82555    IP01      2                                        [001, 001A]
82557    IP06      2                                         [002, 001]

[935 rows x 2 columns]

In [88]:
print(
    f"So, taking in consideration the analysis, we could define our observations ID like the combination of period-farm-zone-tenure-plot:\n"
)
df.groupby(by=["período", "hacienda", "zona", "tenencia", "suerte"]).count()[
    "tch"
].sort_values()

So, taking in consideration the analysis, we could define our observations ID like the combination of period-farm-zone-tenure-plot:

período  hacienda  zona  tenencia  suerte
202407   82515     IP05  11.0      001A      1
                                   001       1
         82506     IP05  11.0      001A      1
         81384     IP03  51.0      003       1
                                   001       1
                                            ..
201701   80123     IP06  11.0      542A      1
         80121     IP01  11.0      047D      1
                                   047A      1
202407   82552     IP01  11.0      043       1
201701   80108     IP06  11.0      324A      1
Name: tch, Length: 21026, dtype: int64

In [89]:
df.shape

(21027, 66)

In [90]:
print(
    f"And also, we could determine the harvests carried out in the same plot or same soil, with the combination of the variables farm-zone-plot. \nWithout the tenure."
)
df.groupby(by=["hacienda", "zona", "suerte"]).count()["tch"].sort_values()

And also, we could determine the harvests carried out in the same plot or same soil, with the combination of the variables farm-zone-plot.
Without the tenure.

hacienda  zona  suerte
80101     IP01  013       1
                013Z      1
82557     IP06  001       1
80298     IP06  040C      1
                030B      1
                         ..
80108     IP06  318       8
80114     IP05  524       8
81363     IP05  231       9
81146     IP05  016       9
80156     IP06  003       9
Name: tch, Length: 5866, dtype: int64

**Comments**

--> An observation ID is the combination of 5 variables: "período-hacienda-zona-tenencia-suerte".  
We found no duplicate observations, because the grouping and counting of the 5 variables match the number of rows in the df.

**Cleaning actions**
1. No cleaning steps are necessary, since there are no duplicate observations.

In [91]:
# rename column periodo
df = df.rename(columns={"período": "periodo"})

## farm and soil identification variables

In [92]:
group_variables = [
    "hacienda",
    "nombre",
    "zona",
    "tenencia",
    "suerte",
    "suelo",
    "area_neta",
    "dist_km",
    "cerca_de",
]

pd.DataFrame(
    {
        "column_format": df[group_variables].dtypes.apply(lambda x: x.name).tolist(),
        "num_unique_values": df[group_variables].nunique().tolist(),
        "num_nan_values": df[group_variables].isna().sum().tolist(),
        "random_data": [
            df[group_variables][col].sample(10).tolist()
            for col in df[group_variables].columns
        ],
    },
    index=df[group_variables].columns,
).sort_values(by="column_format")

,column_format,num_unique_values,num_nan_values,random_data
tenencia,float64,7,1,"[11.0, 51.0, 81.0, 81.0, 51.0, 11.0, 81.0, 51...."
area_neta,float64,2397,0,"[1.69, 7.16, 0.35, 5.85, 7.85, 8.37, 1.7, 10.9..."
dist_km,float64,339,5,"[32.5, 23.5, 43.0, 45.8, 23.5, 7.3, 20.0, 7.3,..."
hacienda,int64,926,0,"[80285, 80666, 81543, 80508, 80331, 80169, 801..."
nombre,object,914,0,"[LA TORTUGA , EL CANELO M, PETITE SAN FELIPE, ..."
zona,object,7,0,"[IP03, IP06, IP05, IP05, IP05, IP05, IP06, IP0..."
suerte,object,1220,0,"[007A, 002, 120, 020, 012A, 001B, 002, 004, 00..."
suelo,object,102,3758,"[GUADUAL, nan, MANUELITA , nan, PALMERAS , LIM..."
cerca_de,object,31,126,"[Yotoco, Palmira, Palmira, Buga, Palmira, El C..."

Nombre

In [93]:
df.nombre.value_counts()

nombre
MARSELLA                      404
ESPERANZA  INESA              330
PETITE SAN FELIPE             272
SAN FERNANDO                  262
PIEDECHINCHE                  249
                             ...
ABROJAL MANUELITA               1
UKRANIA SDOVNIK  P INCAUCA      1
HATO SANTA LUCIA                1
URUBAMBA MANUELITA              1
ORIENTE MANUELITA               1
Name: count, Length: 914, dtype: int64

In [94]:
print(
    f"Some farms (hacienda) have more than one name. This could be due to typos:\ni.e. Farm id #80677 names:\n"
)
print(df[(df["hacienda"] == 80677)].nombre.value_counts())

print(
    f"\nAlso, Some farm names have more than one farm code. This could be due to typos:\ni.e. Farm name CAUCA, IDs:\n"
)
print(df[(df["nombre"] == "CAUCA")].hacienda.value_counts())

Some farms (hacienda) have more than one name. This could be due to typos:
i.e. Farm id #80677 names:

nombre
SINCERIN #4 GRACIELA    4
SINCERIN #4A1           2
Name: count, dtype: int64

Also, Some farm names have more than one farm code. This could be due to typos:
i.e. Farm name CAUCA, IDs:

hacienda
81054    38
82544     8
Name: count, dtype: int64

zona

In [95]:
df.zona.value_counts()

zona
IP05    7813
IP03    5184
IP06    4113
IP01    2307
IP02    1595
ip05      14
IC07       1
Name: count, dtype: int64

tenencia

In [96]:
df.tenencia.value_counts()

tenencia
51.0    9968
31.0    3916
81.0    3528
11.0    3089
28.0     326
91.0     186
82.0      13
Name: count, dtype: int64

suerte

In [97]:
df.suerte.value_counts()

suerte
001     2188
002     1535
003     1249
004      979
005      812
        ...
045B       1
126C       1
009E       1
085C       1
504        1
Name: count, Length: 1220, dtype: int64

suelo

In [98]:
df.suelo.value_counts()

suelo
CORINTIAS             4042
GALPON                2282
PALMIRA               1457
MANUELITA              742
NUEVO PICHICHI         599
                      ...
PUERTO TEJADA            2
BRITANIA-CHUNDULAR       2
JORDAN-NIMA              2
UNION                    1
Sinaí                    1
Name: count, Length: 102, dtype: int64

area_neta y dist_km

In [99]:
df.area_neta.describe()

count    21027.000000
mean         8.642948
std          7.049533
min          0.004000
25%          3.310000
50%          7.000000
75%         12.075000
max         65.000000
Name: area_neta, dtype: float64

In [100]:
print(
    f"Num of soils with less than 1 hectare: -{df[df.area_neta < 1].area_neta.nunique()}-"
)

Num of soils with less than 1 hectare: -140-

In [101]:
df.dist_km.describe()

count    21022.000000
mean        25.311806
std         18.237344
min          1.100000
25%         12.000000
50%         21.900000
75%         32.700000
max        155.000000
Name: dist_km, dtype: float64

In [102]:
df.cerca_de.value_counts().sample(10).sort_values(ascending=False)

cerca_de
El Cerrito       7178
Candelaria        253
Andalucia         224
San Pedro         179
Zarzal            104
Puerto Tejada      97
Caloto             47
Cali               15
Cartago            12
Villa Gorgona       1
Name: count, dtype: int64

**Comments**

-->

**Cleaning actions**
1. We will drop the "nombre" & "tenencia" column, because "nombre" do not give valuable information and have some typos, and "tenencia" neither give valuable information.
2. We will modify the "zona" levels, lowering the letters.
3. All variables belonging to the observation identifier, will be cast to object format.
4. We will modify the "suelo" levels, lowering the letters and replacing the spaces with underscore.
5. We will sort the dataframe according to the identifier of obs.
6. We will modify the "cerca_de" levels, lowering the letters and replacing the spaces with underscore.

In [103]:
# drop column "nombre"
df = df.drop("nombre", axis=1)

# drop column "tenencia"
df = df.drop("tenencia", axis=1)

# lower the levels of variable "zona"
df.zona = df.zona.str.lower()

# Cast hacienda to object format
df[["hacienda"]] = df[["hacienda"]].astype(object)

# modify the levels of "suelo"
df.suelo = df.suelo.str.strip().str.lower().str.replace(" ", "_")

# sort the dataframe
df = df.sort_values(
    by=["periodo", "hacienda", "zona", "suerte", "cod_estado_#"],
    ascending=[True, True, True, True, True],
).reset_index(drop=True)

# modify the levels of "cerca_de"
df.cerca_de = df.cerca_de.str.strip().str.lower().str.replace(" ", "_")

## Crop characteristics

In [104]:
group_variables = [
    "variedad",
    "cod_estado_#",
    "cod_estado",
    "f_siembra",
    "d_s_",
    "edad_ult_cos",
    "f_ult_corte",
    "destino_1=semilla",
    "cod__t_cultivo",
    "cultivo",
    "edad_precosecha",
    "pct_infest_diatrea",
]

pd.DataFrame(
    {
        "column_format": df[group_variables].dtypes.apply(lambda x: x.name).tolist(),
        "num_unique_values": df[group_variables].nunique().tolist(),
        "num_nan_values": df[group_variables].isna().sum().tolist(),
        "random_data": [
            df[group_variables][col].sample(10).tolist()
            for col in df[group_variables].columns
        ],
    },
    index=df[group_variables].columns,
).sort_values(by="column_format")

,column_format,num_unique_values,num_nan_values,random_data
f_siembra,datetime64[ns],3389,0,"[2023-05-19 00:00:00, 2010-04-27 00:00:00, 201..."
f_ult_corte,datetime64[ns],2569,0,"[2019-12-26 00:00:00, 2018-11-15 00:00:00, 201..."
edad_ult_cos,float64,503,0,"[11.83, 11.4, 12.48, 11.43, 14.09, 16.72, 11.8..."
cod__t_cultivo,float64,2,2,"[1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, ..."
edad_precosecha,float64,274,12108,"[11.76, nan, 17.15, nan, nan, nan, nan, nan, n..."
pct_infest_diatrea,float64,5206,15427,"[2.4079, nan, nan, 2.0452, nan, nan, 8.1641, n..."
cod_estado_#,int64,32,0,"[4, 2, 2, 3, 4, 1, 13, 8, 2, 7]"
destino_1=semilla,int64,2,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
variedad,object,58,0,"[RB73-2223, CC01-1940, CC01-1940, CC01-1940, C..."
cod_estado,object,32,0,"[Corte 3, Plantilla, Corte 3, Corte 6, Corte 3..."
d_s_,object,3,13859,"[nan, nan, 1.65, nan, nan, nan, 1.65, 1.65, na..."
cultivo,object,2,2,"[Normal, Normal, Normal, Normal, Normal, Norma..."

f_siembra

In [105]:
df.f_siembra.describe(percentiles=[0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9])

count                            21027
mean     2015-03-11 18:18:44.839492096
min                1986-04-30 00:00:00
2.5%               2001-10-30 00:00:00
5%                 2005-03-15 07:12:00
10%                2009-01-23 14:24:00
20%                2012-07-24 00:00:00
30%                2013-10-17 00:00:00
40%                2015-01-07 00:00:00
50%                2015-11-10 00:00:00
60%                2016-11-28 00:00:00
70%                2018-04-02 00:00:00
80%                2019-01-25 00:00:00
90%      2020-02-29 14:24:00.000000512
max                2023-09-08 00:00:00
Name: f_siembra, dtype: object

In [106]:
print("Descriptive data for some harvest with a sowing date less than 2005:\n")
df[df.f_siembra < "2001-10-30 00:00:00"][
    ["cod_estado_#", "edad_ult_cos", "semanas_mad_", "tch"]
].describe(percentiles=[0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9])

Descriptive data for some harvest with a sowing date less than 2005:

       cod_estado_#  edad_ult_cos  semanas_mad_         tch
count    517.000000    517.000000    261.000000  517.000000
mean      18.094778     13.121180      8.633826  123.922049
std        4.549971      1.619679      3.518913   26.594346
min        2.000000      7.980000      1.285714   47.920245
2.5%       4.900000     10.404000      3.285714   72.660855
5%         8.000000     11.264000      3.571428   79.928291
10%       14.000000     11.560000      4.428571   93.099306
20%       16.000000     11.930000      6.142857  103.123484
30%       17.000000     12.160000      6.857142  110.274168
40%       18.000000     12.390000      7.428571  118.054598
50%       18.000000     12.780000      8.285714  123.541218
60%       19.000000     13.400000      8.857142  129.766203
70%       20.000000     13.860000      9.428571  136.587459
80%       21.000000     14.290000     10.857142  144.303145
90%       23.000000     15.174000     13.428571  154.735170
max       31.000000     19.190000     25.571428  285.900000

In [107]:
temp = df[(df.f_siembra < "2001-10-30 00:00:00") & (df["cod_estado_#"] < 8)].shape[0]
print(f"Harvests with a sowing date before 2001 and less than 8 harvest cuts: {temp}")

Harvests with a sowing date before 2001 and less than 8 harvest cuts: 25

f_ult_corte

In [108]:
df.f_ult_corte.describe(percentiles=[0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9])

count                            21027
mean     2020-10-27 09:01:09.339420672
min                2017-01-02 00:00:00
10%                2017-11-10 00:00:00
20%                2018-07-28 04:48:00
30%                2019-04-28 00:00:00
40%                2020-01-19 00:00:00
50%                2020-10-11 00:00:00
60%                2021-09-01 00:00:00
70%                2022-05-29 00:00:00
80%                2023-02-05 00:00:00
90%                2023-09-20 00:00:00
max                2024-07-10 00:00:00
Name: f_ult_corte, dtype: object

edad_ult_cos

In [109]:
df.edad_ult_cos.describe(
    percentiles=[0.005, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.995]
)

count    21027.00000
mean        13.01111
std          1.97907
min          1.31000
0.5%         7.75000
10%         11.33000
20%         11.79000
30%         12.06000
40%         12.32000
50%         12.62000
60%         13.04000
70%         13.54000
80%         14.26000
90%         15.34000
99.5%       20.66090
max         78.19000
Name: edad_ult_cos, dtype: float64

cod__t_cultivo & cultivo

In [110]:
df.cod__t_cultivo.value_counts()

cod__t_cultivo
1.0    20266
2.0      759
Name: count, dtype: int64

In [111]:
df.cultivo.value_counts()

cultivo
Normal      20266
Organico      759
Name: count, dtype: int64

cod_estado_# & cod_estado

In [112]:
df["cod_estado_#"].value_counts()[0:5]

cod_estado_#
2    2925
1    2823
3    2820
0    2677
4    2378
Name: count, dtype: int64

In [113]:
df["cod_estado_#"].unique()

array([ 1,  8,  0,  3,  2,  5,  4,  6, 17,  7, 14, 13, 12, 15, 16,  9, 19,
       22, 11, 28, 23, 10, 18, 24, 21, 20, 29, 30, 25, 31, 26, 27])

In [114]:
df["cod_estado"].unique()

array(['Corte 1', 'Corte 8', 'Plantilla', 'Corte 3', 'Corte 2', 'Corte 5',
       'Corte 4', 'Corte 6', 'Corte 17', 'Corte 7', 'Corte 14',
       'Corte 13', 'Corte 12', 'Corte 15', 'Corte 16', 'Corte 9',
       'Corte 19', 'Corte 22', 'Corte 11', 'Corte 28', 'Corte 23',
       'Corte 10', 'Corte 18', 'Corte 24', 'Corte 21', 'Corte 20',
       'Corte 29', 'Corte 30', 'Corte 25', 'Corte 31', 'Corte 26',
       'Corte 27'], dtype=object)

destino_1_semilla

In [115]:
df["destino_1=semilla"].value_counts()

destino_1=semilla
0    20733
1      294
Name: count, dtype: int64

In [116]:
df.groupby("destino_1=semilla")[
    ["cod_estado_#", "edad_ult_cos", "m3_riego", "semanas_mad_", "tch"]
].mean()

,cod_estado_#,edad_ult_cos,m3_riego,semanas_mad_,tch
destino_1=semilla,,,,,
0,4.307481,13.064920,25583.661336,9.589695,130.076288
1,1.040816,9.216395,35753.150136,8.795918,96.620507

In [117]:
df[df["destino_1=semilla"] == 1].sample(3)

,periodo,hacienda,zona,suerte,suelo,area_neta,dist_km,variedad,cod_estado_#,cod_estado,f_siembra,d_s_,ult_riego,edad_ult_cos,f_ult_corte,destino_1=semilla,cod__t_cultivo,cultivo,fec_madur_,producto,dosis_madurante,semanas_mad_,tch,edad_precosecha,pct_sac_caña,vejez,tipo_quema,t_corte,cerca_de,cosechó,num_riegos,m3_riego,ddult_riego,lluvias_2_meses_ant_,lluvias_ciclo,lluvias_0__3,lluvias_tres_a_seis,lluvias_seis_a_nueve,luvias_9__fc,pct_infest_diatrea,fosfato_jugo,urea_46pct_,mez,boro_granul_,microzinc,nito_xtend,sul_amonio,nitrax_s,vinaza,codigo_estacion,temp__media_0_3,temp__media_ciclo,temp_max_ciclo,temp_min_ciclo,humedad_rel_media_0_3,humedad_rel_media_ciclo,oscilacion_temp_med_0_3,oscilacion_temp_ciclo,radicion_solar_0_3,radiacion_solar_ciclo,precipitacion_0_3,precipitacion_ciclo,evaporacion_0_3,evaporacion_ciclo
20598,202405,80111,ip06,362,corintias,1.77,8.0,CC05-430,0,Plantilla,2023-07-28,1.65,2024-03-19,9.56,2024-05-15,1,1.0,Normal,NaT,NaN,0.0,NaN,150.222485,NaN,NaN,30.573,SEMILLA,NO DEF.,el_cerrito,AI08,11.0,25581.60,57,277.0,724.0,177.0,156.0,290.0,101.0,NaN,0.0,NaN,NaN,NaN,NaN,750.0,NaN,NaN,14000.0,GIN,31.590,31.596,36.0,15.4,78.736,80.404,18.5,31.596,476.609,464.224,240.3,920.7,479.5,1448.3
5845,201903,80116,ip06,550,nima,15.41,12.0,RB73-2223,5,Corte 5,2013-07-24,1.65,2019-03-24,11.37,2019-08-06,1,1.0,Normal,2019-07-01,BONUS 250 EC REGULADOR FISIOLÓGICO,0.8,5.142857,1.573653,0.16,NaN,NaN,SEMILLA,MANUAL,el_cerrito,ai08,4.0,176139.32,135,62.0,1198.0,352.0,181.0,500.0,165.0,NaN,NaN,NaN,NaN,140.0,NaN,3050.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18384,202307,82506,ip05,002,florida,4.74,42.0,CC05-430,0,Plantilla,2022-10-15,1.65,2023-07-19,6.90,2023-07-29,1,1.0,Normal,NaT,NaN,0.0,NaN,55.978902,NaN,NaN,NaN,SEMILLA,NO DEF.,palmira,AI08,6.0,169108.20,10,47.0,492.0,288.0,186.0,18.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,9200.0,NaN,NaN,NaN,MAR,23.773,24.354,36.0,16.4,76.209,75.217,15.2,24.354,457.452,455.493,283.6,554.5,472.3,1103.6

variedad

In [118]:
df.variedad.unique()

array(['CC01-1940', 'CC85-92', 'CC04-667', 'RB73-2223', 'CC97-7170',
       'CC91-1606', 'CC92-2804', 'SP71-6949', 'CC00-3257', 'CC93-4418',
       'PR61-632', 'V71-51', 'CC84-75', 'CC01-1228', 'CC93-4181',
       'CC98-72', 'CC01-385', 'CC00-3771', 'PR1248', 'PR1141', 'VARIAS',
       'CC03-469', 'CO421', 'RD75-11', 'CC01-746', 'CC01-678',
       'CC00-3885', 'CC93-3895', 'CC82-15', 'CC92-2198', 'CC05-430',
       'CC04-195', 'CC09-235', 'CC09-702', 'CC09-066', 'Q208',
       'RB85-5113', 'CC00-3079', 'CC11-600', 'CC06-783', 'Q191',
       'CC03-1029', 'CC06-791', 'CC09-535', 'CC11-595', 'CC99-2461',
       'CC10-450', 'CC01-1236', 'CC11-605', 'CC05-230', 'CC12-2120',
       'CC09-449', 'CC05-231', 'CC15-2356', 'CC15-2417', 'CC11-2132',
       'CC15-2495', 'MZC74-275'], dtype=object)

In [119]:
df.groupby("variedad").agg({"hacienda": "count", "tch": "mean"}).sample(10).sort_values(
    by="hacienda", ascending=False
)

           hacienda         tch
variedad
CC93-4418      1263  122.434187
PR61-632        117  130.375515
CC91-1606        50   97.060770
CC11-595         38  123.939396
CC03-469          9  113.015207
CC92-2198         5  120.125826
PR1248            4  151.262893
CC06-791          1  135.913333
CC99-2461         1   62.900000
CC00-3079         1  111.813953

pct_infest_diatrea

In [120]:
df.pct_infest_diatrea.describe([0.01, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.99])

count    5600.000000
mean        3.811395
std         2.820273
min         0.000000
1%          0.390906
10%         1.181960
20%         1.719460
30%         2.219450
40%         2.654360
50%         3.139600
60%         3.695700
70%         4.363180
80%         5.373480
90%         7.061140
99%        13.817893
max        29.838700
Name: pct_infest_diatrea, dtype: float64

**Comments**
 
--> we can notice a number of harvests with a **very old sowing date**.  
--> We can notice some crops with **very extreme crop ages (edad_ult_cos)**, these should be analyzed in detail in the EDA.  
--> The columns cod_estado_# & cod_estado refer to the same thing. The same case for the columns cod__t_cultivo & cultivo.  
--> **When the crop is destined for seed, there are no sucrose percentage metrics.** There are also changes in different variables and some columns are NaN values.  
--> We consider that **the column “variedad” is very important for the analysis**, however, we must define how we are going to work with it, if we are going to categorize it or similar.

**Cleaning actions**
1. We will **drop the very old sowing dates with low harvest cuts** to avoid any potential bias in the analysis.  
2. We will **drop the column cod_estado and rename cod_estado_# to num_cosechas**.  
3. We will **drop the column cultivo and rename cod__t_cultivo to cultivo_organico**. After that, substract 1 from the values. 
4. We are going to **eliminate the crops that were intended for seed**. We will assume that we are only working with crops that are intended for production. Also, we will **drop the column destino_1=semilla** .  
5. We will **drop the column d_s_** because it is not relevant for the analysis and inference of tch.  
6. We will **rename the levels of column "variedad"** in order to make it more understandable and easier to work with.

In [121]:
# Eliminate the old sowing dates with low harvest cuts
df = df[~((df.f_siembra < df.f_siembra.quantile(0.025)) & (df["cod_estado_#"] < 8))]

# drop cod_estado and rename cod_estado_#
df.drop("cod_estado", axis=1, inplace=True)
df.rename(columns={"cod_estado_#": "num_cosechas"}, inplace=True)

# drop cultivo and rename cod__t_cultivo, later, subtract 1 from the values
df.drop("cultivo", axis=1, inplace=True)
df.rename(columns={"cod__t_cultivo": "cult_organico"}, inplace=True)
df["cult_organico"] = df["cult_organico"] - 1

# Eliminate crops for seed and drop column destino_1=semilla
df = df[~(df["destino_1=semilla"] == 1)]
df.drop("destino_1=semilla", axis=1, inplace=True)

# Drop column d_s_
df.drop("d_s_", axis=1, inplace=True)

# rename the levels of "variedad"
df["variedad"] = df["variedad"].str.lower().str.replace("-", "_")

## Crop maturity

In [122]:
group_variables = ["fec_madur_", "producto", "dosis_madurante", "semanas_mad_"]

pd.DataFrame(
    {
        "column_format": df[group_variables].dtypes.apply(lambda x: x.name).tolist(),
        "num_unique_values": df[group_variables].nunique().tolist(),
        "num_nan_values": df[group_variables].isna().sum().tolist(),
        "random_data": [
            df[group_variables][col].sample(10).tolist()
            for col in df[group_variables].columns
        ],
    },
    index=df[group_variables].columns,
).sort_values(by="column_format")

,column_format,num_unique_values,num_nan_values,random_data
fec_madur_,datetime64[ns],1210,9480,"[NaT, 2020-04-08 00:00:00, NaT, 2021-04-28 00:..."
dosis_madurante,float64,45,96,"[0.0, 1.1, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0, 1.2, ..."
semanas_mad_,float64,293,9480,"[10.142857, 8.142857, 11.714285, 6.142857, nan..."
producto,object,18,9483,"[nan, BONUS 250 EC REGULADOR FISIOLOGICO, nan,..."

fec_madur_

In [123]:
df.fec_madur_.describe([0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9])

count                            11228
mean     2020-08-27 06:41:17.805486336
min                2016-08-12 00:00:00
2.5%               2017-01-13 00:00:00
5%                 2017-04-26 00:00:00
10%                2017-11-08 00:00:00
20%                2018-07-26 00:00:00
30%                2019-03-27 00:00:00
40%                2019-11-05 00:00:00
50%                2020-07-29 00:00:00
60%                2021-03-26 04:48:00
70%                2022-01-28 00:00:00
80%                2022-11-11 00:00:00
90%                2023-08-24 07:12:00
max                2024-06-24 00:00:00
Name: fec_madur_, dtype: object

dosis_madurante

In [124]:
df.dosis_madurante.describe([0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9])

count    20612.000000
mean         0.543191
std          0.539755
min          0.000000
2.5%         0.000000
5%           0.000000
10%          0.000000
20%          0.000000
30%          0.000000
40%          0.000000
50%          0.600000
60%          0.800000
70%          1.000000
80%          1.100000
90%          1.200000
max          5.000000
Name: dosis_madurante, dtype: float64

In [125]:
temp = df[(df["dosis_madurante"] == 0) | (df["dosis_madurante"].isna())].shape[0]
print(f"Number of values with Nan or equal to zero: -{temp}-")

Number of values with Nan or equal to zero: -9494-

In [126]:
df["dosis_madurante"].value_counts().iloc[0:10]

dosis_madurante
0.0    9398
0.8    3374
1.0    2223
1.2    1978
1.1    1073
0.5     563
1.3     476
0.6     424
1.5     404
1.4     273
Name: count, dtype: int64

semanas_mad_

In [127]:
df.semanas_mad_.describe([0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.99])

count    11228.000000
mean         9.589724
std          5.577488
min         -2.000000
1%           1.428571
5%           3.571428
10%          4.857142
20%          6.142857
30%          7.000000
40%          7.714285
50%          8.571428
60%          9.285714
70%         10.285714
80%         12.142857
99%         31.247143
max         96.285714
Name: semanas_mad_, dtype: float64

In [128]:
(df.semanas_mad_ <= 0).sum()

np.int64(10)

producto

In [129]:
df.producto.value_counts()

producto
BONUS 250 EC REGULADOR FISIOLÓGICO       6983
BONUS 250 EC REGULADOR FISIOLOGICO       3374
COADYUVANTE  DOUCE                        380
FERTILIZANTE LIQUIDO RENDIMIENTO          179
FUSILADE 2000 BL                           84
AGROFOSK-M                                 54
MADURANTE REGULADOR TRONNUSPAC 250 EC      36
FERTILIZANTE ORGÁNICO PATER-M              31
ROUND-UP MONSANTO 747 GRANULADO            29
baykal                                     22
PRODUCTO ENSAYO EN LITROS                  18
MADURANTE BIO SAFE ORGANIC                 17
TRANSLOK                                    7
OTROS MADURANTES                            4
GREEN LIFE                                  3
AMINA 2-4-D                                 2
HERBICIDA CLICK 40 SC                       1
GLIFOLAQ                                    1
Name: count, dtype: int64

**Comments**
 
--> We noticed some crops that say that the maturation was after the cutting of the crop, this is somewhat erroneous.  
--> When there is no information on the maturity date, in the column "dosis_madurante" we find a value of zero, this may be erroneous.  

**Cleaning actions**
1. Drop the observations with "semanas_mad_" lower than 0.0
2. Modify the levels of column "producto", to avoid capital letters and similar.  
3. We will fill the NaN values with "no_especificado" for producto
4. When "semanas_mad" have NaN values, we will place NaN to "dosis_madurante"

In [130]:
# Eliminate crops with maturity weeks less than 0
df = df[~(df["semanas_mad_"] <= 0)]

# modify the levels of column "producto"
df.producto = (
    df.producto.str.replace("FISIOLÓGICO", "FISIOLOGICO")
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

# Fill NaN values of "producto" to "no_especificado"
df.producto = df.producto.fillna("no_especificado")

# Place NaN values to "dosis_madurante" when "semanas_mad" is NaN
df.dosis_madurante = np.where(df.semanas_mad_.isna(), np.nan, df.dosis_madurante)

## Irrigation characteristics

In [131]:
group_variables = [
    "ult_riego",
    "num_riegos",
    "m3_riego",
    "ddult_riego",
    "lluvias_2_meses_ant_",
    "lluvias_ciclo",
    "lluvias_0__3",
    "lluvias_tres_a_seis",
    "lluvias_seis_a_nueve",
    "luvias_9__fc",
]

pd.DataFrame(
    {
        "column_format": df[group_variables].dtypes.apply(lambda x: x.name).tolist(),
        "num_unique_values": df[group_variables].nunique().tolist(),
        "num_nan_values": df[group_variables].isna().sum().tolist(),
        "random_data": [
            df[group_variables][col].sample(10).tolist()
            for col in df[group_variables].columns
        ],
    },
    index=df[group_variables].columns,
).sort_values(by="column_format")

,column_format,num_unique_values,num_nan_values,random_data
ult_riego,datetime64[ns],2234,12497,"[NaT, NaT, NaT, NaT, NaT, NaT, NaT, NaT, 2020-..."
num_riegos,float64,126,12529,"[nan, 2.0, nan, 3.0, nan, nan, nan, 2.0, nan, ..."
m3_riego,float64,6613,0,"[125743.5, 0.0, 0.0, 0.0, 0.0, 0.0, 76680.0, 5..."
lluvias_2_meses_ant_,float64,493,0,"[0.0, 220.0, 0.0, 164.0, 0.0, 72.0, 87.0, 259...."
lluvias_ciclo,float64,2056,0,"[991.0, 916.0, 1200.0, 0.0, 446.0, 917.0, 0.0,..."
lluvias_0__3,float64,641,0,"[0.0, 19.0, 159.0, 355.0, 265.0, 0.0, 431.0, 4..."
lluvias_tres_a_seis,float64,666,0,"[105.0, 223.0, 181.0, 117.0, 73.0, 0.0, 0.0, 1..."
lluvias_seis_a_nueve,float64,638,0,"[241.0, 0.0, 95.0, 0.0, 59.0, 109.0, 89.0, 0.0..."
luvias_9__fc,float64,1097,0,"[0.0, 160.0, 59.0, 0.0, 42.0, 427.0, 0.0, 151...."
ddult_riego,int64,427,0,"[52, 0, 0, 75, 0, 0, 368, 127, 0, 42]"

ult_riego

In [132]:
df.ult_riego.describe([0.02, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9])

count                             8201
mean     2020-02-07 04:13:01.368125952
min                2016-01-12 00:00:00
2%                 2016-08-30 00:00:00
5%                 2016-11-10 00:00:00
10%                2017-03-02 00:00:00
20%                2017-09-28 00:00:00
30%                2018-06-16 00:00:00
40%                2018-09-16 00:00:00
50%                2019-07-31 00:00:00
60%                2020-08-26 00:00:00
70%                2021-10-16 00:00:00
80%                2022-10-04 00:00:00
90%                2023-07-30 00:00:00
max                2024-06-27 00:00:00
Name: ult_riego, dtype: object

num_riegos

In [133]:
df.num_riegos.describe([0.02, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.95])

count    8169.000000
mean        7.287428
std        16.515416
min         1.000000
2%          1.000000
5%          1.000000
10%         2.000000
20%         3.000000
30%         3.000000
40%         4.000000
50%         5.000000
60%         6.000000
70%         7.000000
80%         8.000000
90%        10.000000
95%        12.000000
max       278.000000
Name: num_riegos, dtype: float64

m3_riego & ddult_riego

In [134]:
df[df["ult_riego"].isna()][["num_riegos", "m3_riego", "ddult_riego"]].sum()

num_riegos     0.0
m3_riego       0.0
ddult_riego    0.0
dtype: float64

In [135]:
df[["m3_riego", "ddult_riego"]].describe(
    [0.02, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.95]
)

            m3_riego   ddult_riego
count   20698.000000  20698.000000
mean    25577.711525     45.890617
std     57614.140519     76.816245
min         0.000000      0.000000
2%          0.000000      0.000000
5%          0.000000      0.000000
10%         0.000000      0.000000
20%         0.000000      0.000000
30%         0.000000      0.000000
40%         0.000000      0.000000
50%         0.000000      0.000000
60%         0.000000      0.000000
70%     13499.070000     57.000000
80%     38005.920000     91.000000
90%     84886.200000    152.000000
95%    138558.903000    214.000000
max    772599.600000    853.000000

rain variables

In [136]:
group_variables = [
    "lluvias_2_meses_ant_",
    "lluvias_ciclo",
    "lluvias_0__3",
    "lluvias_tres_a_seis",
    "lluvias_seis_a_nueve",
    "luvias_9__fc",
]

df[group_variables].describe([0.02, 0.05, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.95])

,lluvias_2_meses_ant_,lluvias_ciclo,lluvias_0__3,lluvias_tres_a_seis,lluvias_seis_a_nueve,luvias_9__fc
count,20698.000000,20698.000000,20698.000000,20698.000000,20698.000000,20698.000000
mean,74.129988,523.641183,120.651352,118.767119,117.093530,167.145464
std,97.713990,553.926989,144.564058,143.719974,141.092682,234.201408
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40%,0.000000,78.000000,0.000000,0.000000,0.000000,0.000000
50%,18.000000,436.000000,67.000000,67.000000,67.000000,64.000000
60%,70.000000,657.000000,126.000000,128.000000,126.000000,148.000000
70%,110.000000,836.000000,190.000000,182.000000,181.000000,223.000000
80%,153.000000,1017.000000,254.000000,242.000000,243.000000,322.000000
90%,216.000000,1276.000000,331.000000,324.000000,320.000000,474.000000
95%,269.000000,1498.150000,396.000000,395.000000,388.000000,627.150000
max,902.000000,3917.000000,1028.000000,1050.000000,1075.000000,2752.000000

In [137]:
df[df["lluvias_ciclo"] == 0][group_variables].sum()

lluvias_2_meses_ant_    0.0
lluvias_ciclo           0.0
lluvias_0__3            0.0
lluvias_tres_a_seis     0.0
lluvias_seis_a_nueve    0.0
luvias_9__fc            0.0
dtype: float64

**Comments**
 
--> There are a large number of observations with no data on when the last water irrigation took place. In these cases, the other variables related to irrigation will take the value of zero for that crop.  
--> Observations without rainfall data take the value of zero for all columns.  

**Cleaning actions**
1. The name of the column “luvias_9__fc” will be changed to “lluvia_9_a_cos”.  
  
*With a view to perform imputation steps in the future:*  

2. Observations with a null value in the date of the last irrigation (ult_riego), a null value will be placed in "num_riegos","ddult_riego" and "m3_riego".  
3. Observations with zero values in "lluvias_ciclo", will be changed by a null value.     
4. After the step 3, the observations with null value in "lluvias_ciclo", a null value will be placed in the other rainfall variables.

In [138]:
# change coumn name for luvias_9__fc
df.rename(columns={"luvias_9__fc": "lluvias_9_a_cos"}, inplace=True)

# place null values for irrigation variables
df.num_riegos = np.where(df.ult_riego.isna(), np.nan, df.num_riegos)
df.ddult_riego = np.where(df.ult_riego.isna(), np.nan, df.ddult_riego)
df.m3_riego = np.where(df.ult_riego.isna(), np.nan, df.m3_riego)

# place null values in column "lluvias_ciclo"
df.lluvias_ciclo = np.where(df.lluvias_ciclo == 0, np.nan, df.lluvias_ciclo)

# place null values for other rainfall columns
df.lluvias_2_meses_ant_ = np.where(
    df.lluvias_ciclo.isna(), np.nan, df.lluvias_2_meses_ant_
)
df.lluvias_0__3 = np.where(df.lluvias_ciclo.isna(), np.nan, df.lluvias_0__3)
df.lluvias_tres_a_seis = np.where(
    df.lluvias_ciclo.isna(), np.nan, df.lluvias_tres_a_seis
)
df.lluvias_seis_a_nueve = np.where(
    df.lluvias_ciclo.isna(), np.nan, df.lluvias_seis_a_nueve
)
df.lluvias_9_a_cos = np.where(df.lluvias_ciclo.isna(), np.nan, df.lluvias_9_a_cos)

In [139]:
group_variables = [
    "ult_riego",
    "num_riegos",
    "m3_riego",
    "ddult_riego",
    "lluvias_2_meses_ant_",
    "lluvias_ciclo",
    "lluvias_0__3",
    "lluvias_tres_a_seis",
    "lluvias_seis_a_nueve",
    "lluvias_9_a_cos",
]

pd.DataFrame(
    {
        "column_format": df[group_variables].dtypes.apply(lambda x: x.name).tolist(),
        "num_unique_values": df[group_variables].nunique().tolist(),
        "num_nan_values": df[group_variables].isna().sum().tolist(),
        "random_data": [
            df[group_variables][col].sample(10).tolist()
            for col in df[group_variables].columns
        ],
    },
    index=df[group_variables].columns,
).sort_values(by="column_format")

,column_format,num_unique_values,num_nan_values,random_data
ult_riego,datetime64[ns],2234,12497,"[2018-03-28 00:00:00, 2019-03-09 00:00:00, 202..."
num_riegos,float64,126,12529,"[nan, nan, 8.0, nan, 8.0, 2.0, 5.0, nan, nan, ..."
m3_riego,float64,6612,12497,"[36050.4, nan, 7524.0, 51957.24, 49251.9, 1032..."
ddult_riego,float64,427,12497,"[nan, nan, nan, 99.0, 145.0, 176.0, nan, nan, ..."
lluvias_2_meses_ant_,float64,493,7714,"[nan, nan, nan, 231.0, nan, 317.0, 17.0, nan, ..."
lluvias_ciclo,float64,2055,7714,"[1807.0, 881.0, 755.0, 1142.0, 1102.0, 191.0, ..."
lluvias_0__3,float64,641,7714,"[nan, 270.0, 53.0, 0.0, 116.0, 357.0, 101.0, 3..."
lluvias_tres_a_seis,float64,666,7714,"[8.0, nan, 162.0, 125.0, 118.0, nan, nan, nan,..."
lluvias_seis_a_nueve,float64,638,7714,"[213.0, 102.0, 235.0, nan, nan, 591.0, nan, 17..."
lluvias_9_a_cos,float64,1097,7714,"[0.0, 163.0, 332.0, 268.0, 606.0, nan, 25.0, n..."

## Harvest characteristics

In [140]:
group_variables = ["tipo_quema", "t_corte", "cosechó"]

pd.DataFrame(
    {
        "column_format": df[group_variables].dtypes.apply(lambda x: x.name).tolist(),
        "num_unique_values": df[group_variables].nunique().tolist(),
        "num_nan_values": df[group_variables].isna().sum().tolist(),
        "random_data": [
            df[group_variables][col].sample(10).tolist()
            for col in df[group_variables].columns
        ],
    },
    index=df[group_variables].columns,
).sort_values(by="column_format")

,column_format,num_unique_values,num_nan_values,random_data
tipo_quema,object,4,0,"[VERDE, Q.ACCIDENTAL, VERDE, VERDE, VERDE, VER..."
t_corte,object,3,0,"[MECANIZADO, MECANIZADO, NO DEF., MECANIZADO, ..."
cosechó,object,14,0,"[AI08, AI08, AI08, AI08, AI08, AI08, AI08, AI0..."

In [141]:
df.tipo_quema.value_counts()

tipo_quema
VERDE           16178
Q.ACCIDENTAL     2465
Q.PROGRAMADA     1533
NO DEF.           522
Name: count, dtype: int64

In [142]:
df.t_corte.value_counts()

t_corte
MECANIZADO    17056
MANUAL         3349
NO DEF.         293
Name: count, dtype: int64

In [143]:
df.cosechó.value_counts()

cosechó
AI08    18733
2000     1402
ai08      368
AI01       77
0011       42
0010       18
0001       14
0004       11
2200        9
aI08        9
0006        7
0005        4
0003        2
ai01        2
Name: count, dtype: int64

**Comments**
 
-->  more than 90% of the observations are harvested by the same code.

**Cleaning actions**
1. We **drop the variable “cosechó”**, since we consider that it does not provide sufficient information for the objective.  
2. adjust the column levels for "t_quema" & "t_corte" for better readability.

In [144]:
# drop column cosechó
df.drop("cosechó", axis=1, inplace=True)

# modify the levels of tipo_quema & t_corte
df.tipo_quema = (
    df.tipo_quema.str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace(".", "_")
)

df.t_corte = (
    df.t_corte.str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace(".", "_")
)

## Weather conditions

## Fertilization, supplements and others

# list of pre-processing steps

1.
2.
3.
4.
5.
6.

In [ ]:
# re order the columns
df = df[
    [
        "tch",
        "pct_sac_caña",
        "periodo",
        "hacienda",
        "zona",
        "suerte",
        "suelo",
        "area_neta",
        "dist_km",
        "cerca_de",
        "variedad",
        "cult_organico",
        "num_cosechas",
        "f_siembra",
        "f_ult_corte",
        "edad_ult_cos",
        "edad_precosecha",
        "pct_infest_diatrea",
        "fec_madur_",
        "producto",
        "dosis_madurante",
        "semanas_mad_",
        "ult_riego",
        "ddult_riego",
        "num_riegos",
        "m3_riego",
        "lluvias_2_meses_ant_",
        "lluvias_0__3",
        "lluvias_tres_a_seis",
        "lluvias_seis_a_nueve",
        "lluvias_9_a_cos",
        "lluvias_ciclo",
        "tipo_quema",
        "t_corte",
        "codigo_estacion",
        "temp__media_0_3",
        "temp__media_ciclo",
        "temp_max_ciclo",
        "temp_min_ciclo",
        "humedad_rel_media_0_3",
        "humedad_rel_media_ciclo",
        "oscilacion_temp_med_0_3",
        "oscilacion_temp_ciclo",
        "radicion_solar_0_3",
        "radiacion_solar_ciclo",
        "precipitacion_0_3",
        "precipitacion_ciclo",
        "evaporacion_0_3",
        "evaporacion_ciclo",
        "vinaza",
        "fosfato_jugo",
        "urea_46pct_",
        "mez",
        "boro_granul_",
        "microzinc",
        "nito_xtend",
        "sul_amonio",
        "nitrax_s",
    ]
]

# Export data

In [147]:
# Export df to output DIR --- AWARE-ONLY WHEN NEEDED
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "suertes_clean.csv")
df.to_csv(OUTPUT_FILE)

# resources and bibliography